# Generated by Django 5.2.6 on 2025-11-11 18:55

from django.db import migrations


def create_default_exercises(apps, schema_editor):
    Exercise = apps.get_model('core', 'Exercise')
    
    exercises = [
        # Strength Training
        ('Push-up', 'strength', 'Keep a straight line from head to heels; lower chest near floor; elbows ~45°.'),
        ('Sit-up', 'strength', 'Engage core to lift torso; avoid pulling with neck or lower back.'),
        ('Squat', 'strength', 'Hips back, knees track over toes (not far past); spine neutral.'),
        ('Bench Press', 'strength', 'Stable chest/shoulders/elbows; bar path vertically down and up.'),
        ('Deadlift', 'strength', 'Flat back; coordinate knees and hips; bar travels close to legs.'),
        ('Pull-up', 'strength', 'Control the rhythm up and down; use assisted variations if needed.'),
        ('Lunges', 'strength', 'Front and back knee at safe angles; front knee not beyond toes.'),
        ('Plank', 'strength', 'Body in a straight line; avoid hips too high or sagging.'),
        ('Dips', 'strength', 'Lower body until shoulders are below elbows, then push back up.'),
        ('Overhead Press', 'strength', 'Press weight overhead keeping core tight and back straight.'),
        
        # Cardio
        ('Running', 'cardio', 'Maintain steady pace and proper running form.'),
        ('Cycling', 'cardio', 'Indoor or outdoor cycling for cardiovascular fitness.'),
        ('Burpee', 'cardio', 'Combine squat, push-up, and jump in a smooth sequence.'),
        ('Mountain Climbers', 'cardio', 'Fast and stable pace; use core to control body.'),
        ('Jump Rope', 'cardio', 'Use wrists to turn rope; light on toes with quick rebounds.'),
        ('Rowing', 'cardio', 'Drive sequence: legs → body → arms; recover in reverse order.'),
        ('Jumping Jacks', 'cardio', 'Jump with arms and legs spreading wide, then return to start.'),
        
        # Flexibility
        ('Stretching', 'flexibility', 'Hold stretches for 15-30 seconds, don\'t bounce.'),
        ('Yoga Flow', 'flexibility', 'Continuous sequence of yoga poses with breath coordination.'),
        
        # Other
        ('Rest', 'other', 'Active or passive rest period.'),
        ('Warm-up', 'other', 'Light activity to prepare body for exercise.'),
        ('Cool-down', 'other', 'Light activity to help body recover after exercise.')
    ]
    
    for name, category, description in exercises:
        Exercise.objects.get_or_create(
            name=name,
            defaults={
                'category': category,
                'description': description
            }
        )


def reverse_create_default_exercises(apps, schema_editor):
    Exercise = apps.get_model('core', 'Exercise')
    Exercise.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exercise_workoutsession_exerciseset'),
    ]

    operations = [
        migrations.RunPython(create_default_exercises, reverse_create_default_exercises),
    ]
