# Generated by Django 5.2.6 on 2025-11-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_passwordresetcode'),
        ('core', '0004_auto_20251111_1255'),
    ]

    operations = [
    ]
